.balign 0x800
.global exception_table_el2
exception_table_el2:
current_el_sp0_sync:
// TODO: exception handler for the synchronous exception from current EL using sp0

.balign 0x80
current_el_sp0_irq:
// TODO

.balign 0x80
current_el_sp0_fiq:
// TODO

.balign 0x80
current_el_sp0_serror:
// TODO

.balign 0x80
current_el_spx_sync:
// TODO

.balign 0x80
current_el_spx_irq:
// TODO

.balign 0x80
current_el_spx_fiq:
// TODO

.balign 0x80
current_el_spx_serror:
// TODO

.balign 0x80
lower_el_aarch64_sync:
// TODO

.balign 0x80
lower_el_aarch64_irq:
// TODO

.balign 0x80
lower_el_aarch64_fiq:
// TODO

.balign 0x80
lower_el_aarch64_serror:
// TODO

.balign 0x80
lower_el_aarch32_sync:
// TODO

.balign 0x80
lower_el_aarch32_irq:
// TODO

.balign 0x80
lower_el_aarch32_fiq:
// TODO

.balign 0x80
lower_el_aarch32_serror:
// TODO

