name: SynestiaOS

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build-on-linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        shell: bash
        run: sudo apt-get update && sudo apt-get install --fix-missing -y build-essential binutils make cmake clang llvm lld

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/CMake/Toolchain/ToolchainClang.cmake ..

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - uses: actions/upload-artifact@v2
        with:
          name: build-on-linux-${{env.BUILD_TYPE}}
          path: ${{runner.workspace}}/

  build-on-mac:
    if: true # change it to true to build on mac
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        shell: bash
        run: brew install iwyu llvm

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: export PATH="/usr/local/opt/llvm/bin:$PATH" && cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/CMake/Toolchain/ToolchainClang.cmake ..

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: export PATH="/usr/local/opt/llvm/bin:$PATH" && cmake --build . --config $BUILD_TYPE

      - uses: actions/upload-artifact@v2
        with:
          name: build-on-mac-${{env.BUILD_TYPE}}
          path: ${{runner.workspace}}/
